apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: {{ .Values.namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  type: ClusterIP
  ports:
    - name: "ui"
      port: 8080
      targetPort: 8080
    - name: "jnlp"
      port: 50000
      targetPort: 50000